name: Performance Tests (k6)

on:
  push:
    branches:
      - main
      - segunda-branch
  pull_request:
    branches:
      - main

jobs:
  k6_test:
    runs-on: ubuntu-latest
    container:
      image: loadimpact/k6
      options: --memory=2g --cpus=2  --user root 

    env:
      BASE_URL: ${{ secrets.BASE_URL }}  # URL da API
      K6_WEB_DASHBOARD: true             # Gera dashboard
      K6_WEB_DASHBOARD_EXPORT: report.html

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar o k6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg2 ca-certificates
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor --output /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb/ stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Validar se os arquivos de teste existem
        run: |
          echo "Listando arquivos do projeto"
          ls -R

      - name: Rodar testes de performance (GET Readers)
        run: |
          k6 run tests/reader-register.js
          

      - name: Rodar testes de performance (GET Users)
        run: |
          k6 run tests/login_valido.tests.js


      - name: Rodar testes de performance (POST Books)
        run: |
          k6 run tests/book_register.js    

      - name: Rodar testes de performance (GET Books)
        run: |
          k6 run tests/books_list.js

      - name: Rodar testes de performance (Exchange Books)
        run: |
          k6 run tests/books_exchange.js


      - name: Upload do relatório gerado (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: k6-performance-report
          path: report.html
